
include ${MAXNET}/project/linux/makebase/make_begin


MODULE			= dll

LIBA_FILE 		= libsdu.a
LIBSO_FILE		= 
EXEC_FILE 		=

INLIB_FILE		=
INLIB_DIR		= 
INC_PATH 		= -I${MAXNET_INC_DIR} -I${MAXNET_INC_DIR}/dll/sdu -I${MAXNET_INC_DIR}/dll/sdu/detail -I${MAXNET_INC_DIR}/dll/sdu/algorithm -I${THIRDP_DIR}/tinyxml/include -I${THIRDP_DIR}/sqlite -I/usr/local/mysql/include -I/usr/share/gettext/intl


include ${MAXNET}/project/linux/makebase/make_end
