public:
	ESaveState			m_eBagSaveState;//  Bag±£´æ×´Ì¬
	ESaveState			m_eBuildSaveState;//  Build±£´æ×´Ì¬
	ESaveState			m_eCurstateSaveState;//  Curstate±£´æ×´Ì¬
	ESaveState			m_eCurtaskSaveState;//  Curtask±£´æ×´Ì¬
	ESaveState			m_eEnemySaveState;//  Enemy±£´æ×´Ì¬
	ESaveState			m_eEquipSaveState;// Equip±£´æ×´Ì¬
	ESaveState			m_eGoodsSaveState;//  Goods±£´æ×´Ì¬
	ESaveState			m_eHeroSaveState;//  Hero±£´æ×´Ì¬
	ESaveState			m_eCommonBattleRcdSaveState;//  CommonBattleRcd±£´æ×´Ì¬
	ESaveState			m_eEliteBattleRcdSaveState;//  EliteBattleRcd±£´æ×´Ì¬
	ESaveState			m_eCommonInstanceDataSaveState;//  CommonInstanceData±£´æ×´Ì¬
	ESaveState			m_eEliteInstanceDataSaveState;//  EliteInstanceData±£´æ×´Ì¬
	ESaveState			m_eLocaleSaveState;//  Locale±£´æ×´Ì¬
	ESaveState			m_eLoginEncourageRecordSaveState;//  LoginEncourageRecord±£´æ×´Ì¬
	ESaveState			m_eMoneyTreeSaveState;//  MoneyTree±£´æ×´Ì¬
	ESaveState			m_eOnhookRecordSaveState;//  OnhookRecord±£´æ×´Ì¬
	ESaveState			m_eOnlineEncourageRecordSaveState;//  OnlineEncourageRecord±£´æ×´Ì¬
	ESaveState			m_ePhystrengthSaveState;//  Phystrength±£´æ×´Ì¬
	ESaveState			m_ePlunderBaseSaveState;//  PlunderBase±£´æ×´Ì¬
	ESaveState			m_ePlunderBattleLogSaveState;//  PlunderBattleLog±£´æ×´Ì¬
	ESaveState			m_ePlunderCaptureSaveState;//  PlunderCapture±£´æ×´Ì¬
	ESaveState			m_ePlunderWorkLogSaveState;//  PlunderWorkLog±£´æ×´Ì¬
	ESaveState			m_ePlundeWorkPosSaveState;//  PlundeWorkPos±£´æ×´Ì¬
	ESaveState			m_eRaceSaveState;//  Race±£´æ×´Ì¬
	ESaveState			m_eRaceBattleLogSaveState;//  RaceBattleLog±£´æ×´Ì¬
	ESaveState			m_eSkillSaveState;//  Skill±£´æ×´Ì¬