include ${MAXNET}/project/linux/makebase/make_begin


MODULE			= dll

LIBA_FILE 		= libsdlogger.a
LIBSO_FILE		= 
EXEC_FILE 		=

COMP_OBJ		= ${COMM_OBJ}
INLIB_FILE		=
INLIB_DIR		= 
INC_PATH 		= -I${MAXNET_INC_DIR} -I${MAXNET_INC_DIR}/dll/sdu -I${MAXNET_INC_DIR}/dll/sdlogger -I${THIRDP_DIR}/tinyxml/include -I/usr/share/gettext/intl


include ${MAXNET}/project/linux/makebase/make_end
