//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: client.proto
namespace Msg.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private int _clientVersion;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientVersion
    {
      get { return _clientVersion; }
      set { _clientVersion = value; }
    }
    private string _deviceid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"deviceid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deviceid
    {
      get { return _deviceid; }
      set { _deviceid = value; }
    }
    private string _notifyid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"notifyid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string notifyid
    {
      get { return _notifyid; }
      set { _notifyid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _zoneid;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private int _userid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private int _playerid;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private string _job;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string job
    {
      get { return _job; }
      set { _job = value; }
    }
    private Msg.Protocol.LoginReq.LoginType _loginType;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"loginType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Msg.Protocol.LoginReq.LoginType loginType
    {
      get { return _loginType; }
      set { _loginType = value; }
    }
    private int _authType;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"authType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int authType
    {
      get { return _authType; }
      set { _authType = value; }
    }
    private string _authKey;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"authKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string authKey
    {
      get { return _authKey; }
      set { _authKey = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LoginType")]
    public enum LoginType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewRole", Value=0)]
      NewRole = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OldRole", Value=1)]
      OldRole = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReply")]
  public partial class LoginReply : global::ProtoBuf.IExtensible
  {
    public LoginReply() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LoginType")]
    public enum LoginType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewRole", Value=0)]
      NewRole = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OldRole", Value=1)]
      OldRole = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EncryptKeyNtf")]
  public partial class EncryptKeyNtf : global::ProtoBuf.IExtensible
  {
    public EncryptKeyNtf() {}
    
    private string _publicKey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"publicKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string publicKey
    {
      get { return _publicKey; }
      set { _publicKey = value; }
    }
    private string _privateKey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"privateKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string privateKey
    {
      get { return _privateKey; }
      set { _privateKey = value; }
    }
    private string _authKey;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"authKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string authKey
    {
      get { return _authKey; }
      set { _authKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthReq")]
  public partial class AuthReq : global::ProtoBuf.IExtensible
  {
    public AuthReq() {}
    
    private string _authKey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"authKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string authKey
    {
      get { return _authKey; }
      set { _authKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthAck")]
  public partial class AuthAck : global::ProtoBuf.IExtensible
  {
    public AuthAck() {}
    
    private Msg.Protocol.AuthResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Msg.Protocol.AuthResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _encryptKey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"encryptKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string encryptKey
    {
      get { return _encryptKey; }
      set { _encryptKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingPong")]
  public partial class PingPong : global::ProtoBuf.IExtensible
  {
    public PingPong() {}
    
    private string _pingpong;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pingpong", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pingpong
    {
      get { return _pingpong; }
      set { _pingpong = value; }
    }
    private ulong _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyRequest")]
  public partial class ReadyRequest : global::ProtoBuf.IExtensible
  {
    public ReadyRequest() {}
    
    private int _is_ready;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_ready", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int is_ready
    {
      get { return _is_ready; }
      set { _is_ready = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveRequest")]
  public partial class MoveRequest : global::ProtoBuf.IExtensible
  {
    public MoveRequest() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveNotify")]
  public partial class MoveNotify : global::ProtoBuf.IExtensible
  {
    public MoveNotify() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ClientMsgId")]
    public enum ClientMsgId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientMsg_LoginRequest", Value=1)]
      ClientMsg_LoginRequest = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientMsg_AuthRequest", Value=2)]
      ClientMsg_AuthRequest = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientMsg_PingRequest", Value=3)]
      ClientMsg_PingRequest = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientMsg_SpeedTestRequest", Value=4)]
      ClientMsg_SpeedTestRequest = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientMsg_LatencyTestRequest", Value=5)]
      ClientMsg_LatencyTestRequest = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientMsg_RouteToGate", Value=1000)]
      ClientMsg_RouteToGate = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientMsg_ReadyRequest", Value=1001)]
      ClientMsg_ReadyRequest = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientMsg_MoveRequest", Value=1002)]
      ClientMsg_MoveRequest = 1002
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ServerMsgId")]
    public enum ServerMsgId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerMsg_LoginReply", Value=1)]
      ServerMsg_LoginReply = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerMsg_EncryptKeyNotify", Value=2)]
      ServerMsg_EncryptKeyNotify = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerMsg_AutyReply", Value=3)]
      ServerMsg_AutyReply = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerMsg_PongReply", Value=4)]
      ServerMsg_PongReply = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerMsg_SpeedTestReply", Value=5)]
      ServerMsg_SpeedTestReply = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerMsg_LatencyTestReply", Value=6)]
      ServerMsg_LatencyTestReply = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientMsg_MoveNotify", Value=1001)]
      ClientMsg_MoveNotify = 1001
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EncryptKeyDef")]
    public enum EncryptKeyDef
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EncryptKeyLen", Value=32)]
      EncryptKeyLen = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EncryptHeadLen", Value=2)]
      EncryptHeadLen = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EncryptTailLen", Value=4)]
      EncryptTailLen = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AuthKeyLen", Value=16)]
      AuthKeyLen = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PublicKeyLen", Value=8)]
      PublicKeyLen = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PrivateKeyLen", Value=20)]
      PrivateKeyLen = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AuthResult")]
    public enum AuthResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUTH_OK", Value=0)]
      AUTH_OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUTH_FAIL", Value=1)]
      AUTH_FAIL = 1
    }
  
}