include ${MAXNET}/project/linux/makebase/make_begin


MODULE			= dll

LIBA_FILE 		= libsdframework.a
LIBSO_FILE		= 
EXEC_FILE 		=

COMP_OBJ		= ${COMM_OBJ}
INLIB_FILE		=
INLIB_DIR		= 
INC_PATH 		= -I${MAXNET_INC_DIR} -I${MAXNET_INC_DIR}/dll/sdu -I${MAXNET_INC_DIR}/dll/sdlogger -I${MAXNET_INC_DIR}/dll/sdframework -I${MAXNET_INC_DIR}/dll/sdconsole -I${MAXNET_INC_DIR}/dll/sdnet -I${MAXNET_INC_DIR}/dll/sdpipe -I${THIRDP_DIR}/tinyxml/include -I/usr/share/gettext/intl -I${MAXNET_INC_DIR}/dll/sddb


include ${MAXNET}/project/linux/makebase/make_end
