include ${MAXNET}/project/linux/makebase/make_begin


MODULE			= tool

LIBA_FILE 		= 
LIBSO_FILE		= 
EXEC_FILE 		= pipeinfoview

OTHER_SRC_C	= 
OTHER_SRC_CPP   = 

INLIB_FILE		= -ldl -liconv -lcharset -lsdu 
INLIB_DIR		= -L${THIRDP_DIR}/tinyxml/lib/linux64/debug -L/usr/local/lib -L/usr/local/lib64 
INC_PATH 		= -I${MAXNET_INC_DIR} -I${MAXNET_INC_DIR}/dll -I${MAXNET_INC_DIR}/dll/sdu 



include ${MAXNET}/project/linux/makebase/make_end
